version: '3.8'
services:
  api:
    container_name: easy_control_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=easy_control_db;Username=admin;Password=admin123;
    depends_on:
      - db
  db:
    container_name: easy_control_db
    image: postgres:13
    environment:
      - POSTGRES_DB=easy_control_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
  pgadmin:
    container_name: easy_control_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin123
    ports:
      - '5050:80'
